<template>
  <v-card class="pa-3 wrapper mb-1">
     <v-container grid-list-sm>
      <v-layout row wrap>
        <v-flex class="pa-0" xs12 sm12 md12>
          <h3 class="subheading">Jobs By Locations</h3>
          <v-divider class="my-2"></v-divider>
          <div class="jLBx">
            <ul class="px-4">
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Metro Manila&amp;reg=1&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Metro Manila&amp;reg=1&amp;vt=jobs-by-location">Metro Manila</a> - <span class="">203 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Abra&amp;reg=2&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Abra&amp;reg=2&amp;vt=jobs-by-location">Abra</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Agusan del Norte&amp;reg=3&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Agusan del Norte&amp;reg=3&amp;vt=jobs-by-location">Agusan del Norte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Agusan del Sur&amp;reg=4&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Agusan del Sur&amp;reg=4&amp;vt=jobs-by-location">Agusan del Sur</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Aklan&amp;reg=5&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Aklan&amp;reg=5&amp;vt=jobs-by-location">Aklan</a> - <span class="">1 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Albay&amp;reg=6&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Albay&amp;reg=6&amp;vt=jobs-by-location">Albay</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Antique&amp;reg=7&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Antique&amp;reg=7&amp;vt=jobs-by-location">Antique</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Apayao&amp;reg=8&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Apayao&amp;reg=8&amp;vt=jobs-by-location">Apayao</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Aurora&amp;reg=9&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Aurora&amp;reg=9&amp;vt=jobs-by-location">Aurora</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Basilan&amp;reg=10&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Basilan&amp;reg=10&amp;vt=jobs-by-location">Basilan</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Bataan&amp;reg=11&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Bataan&amp;reg=11&amp;vt=jobs-by-location">Bataan</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Batanes&amp;reg=12&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Batanes&amp;reg=12&amp;vt=jobs-by-location">Batanes</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Batangas&amp;reg=13&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Batangas&amp;reg=13&amp;vt=jobs-by-location">Batangas</a> - <span class="">4 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Benguet&amp;reg=14&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Benguet&amp;reg=14&amp;vt=jobs-by-location">Benguet</a> - <span class="">1 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Biliran&amp;reg=15&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Biliran&amp;reg=15&amp;vt=jobs-by-location">Biliran</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Bohol&amp;reg=16&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Bohol&amp;reg=16&amp;vt=jobs-by-location">Bohol</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Bukidnon&amp;reg=17&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Bukidnon&amp;reg=17&amp;vt=jobs-by-location">Bukidnon</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Bulacan&amp;reg=18&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Bulacan&amp;reg=18&amp;vt=jobs-by-location">Bulacan</a> - <span class="">2 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Cagayan&amp;reg=19&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Cagayan&amp;reg=19&amp;vt=jobs-by-location">Cagayan</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Camarines Norte&amp;reg=20&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Camarines Norte&amp;reg=20&amp;vt=jobs-by-location">Camarines Norte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Camarines Sur&amp;reg=21&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Camarines Sur&amp;reg=21&amp;vt=jobs-by-location">Camarines Sur</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Camiguin&amp;reg=22&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Camiguin&amp;reg=22&amp;vt=jobs-by-location">Camiguin</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Capiz&amp;reg=23&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Capiz&amp;reg=23&amp;vt=jobs-by-location">Capiz</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Catanduanes&amp;reg=24&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Catanduanes&amp;reg=24&amp;vt=jobs-by-location">Catanduanes</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Cavite&amp;reg=25&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Cavite&amp;reg=25&amp;vt=jobs-by-location">Cavite</a> - <span class="">16 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Cebu&amp;reg=26&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Cebu&amp;reg=26&amp;vt=jobs-by-location">Cebu</a> - <span class="">1 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Compostela Valley&amp;reg=27&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Compostela Valley&amp;reg=27&amp;vt=jobs-by-location">Compostela Valley</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=North Cotabato&amp;reg=28&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=North Cotabato&amp;reg=28&amp;vt=jobs-by-location">North Cotabato</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Davao del Norte&amp;reg=29&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Davao del Norte&amp;reg=29&amp;vt=jobs-by-location">Davao del Norte</a> - <span class="">2 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Davao del Sur&amp;reg=30&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Davao del Sur&amp;reg=30&amp;vt=jobs-by-location">Davao del Sur</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Davao Occidental&amp;reg=31&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Davao Occidental&amp;reg=31&amp;vt=jobs-by-location">Davao Occidental</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Davao Oriental&amp;reg=32&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Davao Oriental&amp;reg=32&amp;vt=jobs-by-location">Davao Oriental</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Dinagat Islands&amp;reg=33&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Dinagat Islands&amp;reg=33&amp;vt=jobs-by-location">Dinagat Islands</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Eastern Samar&amp;reg=34&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Eastern Samar&amp;reg=34&amp;vt=jobs-by-location">Eastern Samar</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Guimaras&amp;reg=35&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Guimaras&amp;reg=35&amp;vt=jobs-by-location">Guimaras</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Ifugao&amp;reg=36&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Ifugao&amp;reg=36&amp;vt=jobs-by-location">Ifugao</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Ilocos Norte&amp;reg=37&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Ilocos Norte&amp;reg=37&amp;vt=jobs-by-location">Ilocos Norte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Ilocos Sur&amp;reg=38&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Ilocos Sur&amp;reg=38&amp;vt=jobs-by-location">Ilocos Sur</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Iloilo&amp;reg=39&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Iloilo&amp;reg=39&amp;vt=jobs-by-location">Iloilo</a> - <span class="">5 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Isabela&amp;reg=40&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Isabela&amp;reg=40&amp;vt=jobs-by-location">Isabela</a> - <span class="">4 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Kalinga&amp;reg=41&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Kalinga&amp;reg=41&amp;vt=jobs-by-location">Kalinga</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=La Union&amp;reg=42&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=La Union&amp;reg=42&amp;vt=jobs-by-location">La Union</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Laguna&amp;reg=43&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Laguna&amp;reg=43&amp;vt=jobs-by-location">Laguna</a> - <span class="">6 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Lanao del Norte&amp;reg=44&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Lanao del Norte&amp;reg=44&amp;vt=jobs-by-location">Lanao del Norte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Lanao del Sur&amp;reg=45&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Lanao del Sur&amp;reg=45&amp;vt=jobs-by-location">Lanao del Sur</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Leyte&amp;reg=46&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Leyte&amp;reg=46&amp;vt=jobs-by-location">Leyte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Maguindanao&amp;reg=47&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Maguindanao&amp;reg=47&amp;vt=jobs-by-location">Maguindanao</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Marinduque&amp;reg=48&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Marinduque&amp;reg=48&amp;vt=jobs-by-location">Marinduque</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Masbate&amp;reg=49&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Masbate&amp;reg=49&amp;vt=jobs-by-location">Masbate</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Misamis Occidental&amp;reg=50&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Misamis Occidental&amp;reg=50&amp;vt=jobs-by-location">Misamis Occidental</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Misamis Oriental&amp;reg=51&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Misamis Oriental&amp;reg=51&amp;vt=jobs-by-location">Misamis Oriental</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Mountain Province&amp;reg=52&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Mountain Province&amp;reg=52&amp;vt=jobs-by-location">Mountain Province</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Negros Occidental&amp;reg=53&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Negros Occidental&amp;reg=53&amp;vt=jobs-by-location">Negros Occidental</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Negros Oriental&amp;reg=54&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Negros Oriental&amp;reg=54&amp;vt=jobs-by-location">Negros Oriental</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Northern Samar&amp;reg=55&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Northern Samar&amp;reg=55&amp;vt=jobs-by-location">Northern Samar</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Nueva Ecija&amp;reg=56&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Nueva Ecija&amp;reg=56&amp;vt=jobs-by-location">Nueva Ecija</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Nueva Vizcaya&amp;reg=57&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Nueva Vizcaya&amp;reg=57&amp;vt=jobs-by-location">Nueva Vizcaya</a> - <span class="">1 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Occidental Mindoro&amp;reg=58&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Occidental Mindoro&amp;reg=58&amp;vt=jobs-by-location">Occidental Mindoro</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Oriental Mindoro&amp;reg=59&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Oriental Mindoro&amp;reg=59&amp;vt=jobs-by-location">Oriental Mindoro</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Palawan&amp;reg=60&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Palawan&amp;reg=60&amp;vt=jobs-by-location">Palawan</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Pampanga&amp;reg=61&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Pampanga&amp;reg=61&amp;vt=jobs-by-location">Pampanga</a> - <span class="">2 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Pangasinan&amp;reg=62&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Pangasinan&amp;reg=62&amp;vt=jobs-by-location">Pangasinan</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Quezon&amp;reg=63&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Quezon&amp;reg=63&amp;vt=jobs-by-location">Quezon</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Quirino&amp;reg=64&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Quirino&amp;reg=64&amp;vt=jobs-by-location">Quirino</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Rizal&amp;reg=65&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Rizal&amp;reg=65&amp;vt=jobs-by-location">Rizal</a> - <span class="">2 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Romblon&amp;reg=66&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Romblon&amp;reg=66&amp;vt=jobs-by-location">Romblon</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Samar&amp;reg=67&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Samar&amp;reg=67&amp;vt=jobs-by-location">Samar</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Sarangani&amp;reg=68&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Sarangani&amp;reg=68&amp;vt=jobs-by-location">Sarangani</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Siquijor&amp;reg=69&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Siquijor&amp;reg=69&amp;vt=jobs-by-location">Siquijor</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Sorsogon&amp;reg=70&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Sorsogon&amp;reg=70&amp;vt=jobs-by-location">Sorsogon</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=South Cotabato&amp;reg=71&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=South Cotabato&amp;reg=71&amp;vt=jobs-by-location">South Cotabato</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Southern Leyte&amp;reg=72&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Southern Leyte&amp;reg=72&amp;vt=jobs-by-location">Southern Leyte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Sultan Kudarat&amp;reg=73&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Sultan Kudarat&amp;reg=73&amp;vt=jobs-by-location">Sultan Kudarat</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Sulu&amp;reg=74&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Sulu&amp;reg=74&amp;vt=jobs-by-location">Sulu</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Surigao del Norte&amp;reg=75&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Surigao del Norte&amp;reg=75&amp;vt=jobs-by-location">Surigao del Norte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Surigao del Sur&amp;reg=76&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Surigao del Sur&amp;reg=76&amp;vt=jobs-by-location">Surigao del Sur</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Tarlac&amp;reg=77&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Tarlac&amp;reg=77&amp;vt=jobs-by-location">Tarlac</a> - <span class="">1 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Tawi-Tawi&amp;reg=78&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Tawi-Tawi&amp;reg=78&amp;vt=jobs-by-location">Tawi-Tawi</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Zambales&amp;reg=79&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Zambales&amp;reg=79&amp;vt=jobs-by-location">Zambales</a> - <span class="">1 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Zamboanga del Norte&amp;reg=80&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Zamboanga del Norte&amp;reg=80&amp;vt=jobs-by-location">Zamboanga del Norte</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Zamboanga del Sur&amp;reg=81&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Zamboanga del Sur&amp;reg=81&amp;vt=jobs-by-location">Zamboanga del Sur</a> - <span class="">0 jobs</span></li>
                <li class="fs-13"><a href="https://jobfair-online.net/jobs?location=Zamboanga Sibugay&amp;reg=82&amp;vt=jobs-by-location" target="https://jobfair-online.net/jobs?location=Zamboanga Sibugay&amp;reg=82&amp;vt=jobs-by-location">Zamboanga Sibugay</a> - <span class="">0 jobs</span></li>
            </ul>
          </div>
        </v-flex>
      </v-layout>
    </v-container>
  </v-card>
</template>

<script>
export default {

}
</script>

<style>
  .jLBx{
    max-height: 250px;
    overflow-y: scroll;
  }
</style>
